<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <NoWarn>$(NoWarn);CS8602;CS8604;xUnit1031</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Avalonia.Headless.XUnit" Version="11.3.20" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.20" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpCommander.Core\SharpCommander.Core.csproj" />
    <ProjectReference Include="..\..\src\SharpCommander.Desktop\SharpCommander.Desktop.csproj" />
  </ItemGroup>
</Project>
